version: '3.8'
services:
  # setup:
  #   build: ./setup
  #   volumes:
  #     - .:/app

  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data  
      - ./database:/docker-entrypoint-initdb.d
    # depends_on:
    #   - setup

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - database

  # frontend:
  #     build: 
  #       context: ./frontend
  #       args: 
  #         - REACT_APP_API_HOST=${REACT_APP_API_HOST}
  #         - REACT_APP_API_PORT=${REACT_APP_API_PORT}
  #     env_file:
  #     - .env
  #     ports:
  #       - "${REACT_APP_PORT}:${REACT_APP_NGINX_PORT}"
  #     volumes:
  #       - ./frontend:/app
  #     environment:
  #       REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  #       REACT_APP_API_PORT: ${REACT_APP_API_PORT}
  #     depends_on:
  #       - backend
  #       - setup

volumes:
  postgres-data: