apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
