name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests_backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run docker compose
      run: |
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
        POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
        POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
        FASTAPI_PORT=${{ secrets.FASTAPI_PORT }} \
        REACT_APP_API_HOST=${{ secrets.REACT_APP_API_HOST }} \
        REACT_APP_API_PORT=${{ secrets.REACT_APP_API_PORT }} \
        REACT_APP_PORT=${{ secrets.REACT_APP_PORT }} \
        REACT_APP_NGINX_PORT=${{ secrets.REACT_APP_NGINX_PORT }} \
        docker compose up -d

    - name: Install packages in docker container
      run: |
        docker exec spreadsheet-db-backend-1 pip install coverage pytest coveralls

    - name: Run tests with coverage
      run: |
        docker exec spreadsheet-db-backend-1 coverage run -m pytest

    - name: Generate coverage report
      run: |
        docker exec spreadsheet-db-backend-1 coverage report
        docker exec spreadsheet-db-backend-1 coverage xml

    - name: Upload coverage to coveralls
      run: |
        docker exec -e COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }} spreadsheet-db-backend-1 coveralls
